//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Friendly.DATA.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FriendlyEntities : DbContext
    {
        public FriendlyEntities()
            : base("name=FriendlyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<ApplicationStatus> ApplicationStatuses { get; set; }
        public virtual DbSet<Clique> Cliques { get; set; }
        public virtual DbSet<Friendship> Friendships { get; set; }
        public virtual DbSet<OpenFriendship> OpenFriendships { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
    }
}
