//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Friendly.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenFriendship
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OpenFriendship()
        {
            this.Applications = new HashSet<Application>();
        }
    
        public int OpenFriendshipId { get; set; }
        public int FriendshipId { get; set; }
        public int CliqueId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application> Applications { get; set; }
        public virtual Clique Clique { get; set; }
        public virtual Friendship Friendship { get; set; }
    }
}
